config/routes.rb
Rails.application.routes.draw do

root "authors#index"

resources :authors
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :current_author, only: [:show, :edit, :update, :destroy]
  def index
    @authors = Author.all
  end

  def show

  end

  def new
    @author = Author.new
  end

  def create
    author = Author.new(author_params)
    author.save
    redirect_to author
  end

  def edit

  end

  def update
    @author.update(author_params)
    redirect_to @author
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  def author_params
    params.require(:author).permit(:name, :book)
  end

private

def current_author
  @author ||= Author.find_by(id: params[:id])
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |form| %>

  <table>
    <tbody>
      <tr>
        <td><%= form.label :name %></td>
        <td><%= form.text_field :name %></td>
      </tr>

      <tr>
        <td><%= form.label :book %></td>
        <td><%= form.text_field :book %></td>
      </tr>
    </tbody>
  </table>
<%= form.submit "Save" %>
<% end %>

app/views/authors/edit.html.erb
<%= render "form" %>

app/views/authors/index.html.erb
<%= link_to "New", new_author_path %>
  <table border="1">
    <thead>
      <th>Name</th>
      <th>Book</th>
      <th colspan="3"></th>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.name %></td>
          <td><%= author.book %></td>
            <td><%= link_to "Show", author %></td>
            <td><%= link_to "Edit", adit_author_path(author) %></td>
            <td><%= link_to "Delete", author, method: :delete %>
          </tr>
      <% end %>
    </tbody>
  </table>

app/views/authors/new.html.erb
<% render "form" %>

app/views/authors/show.html.erb
<%= link_to "Back", authors_path %>
  <p>
    <strong>Name: </strong>
      <%= @author.name %>
  </p>

  <p>
    <strong>Book: </strong>
      <%= @author.book %>
  </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>